spring.datasource.url=jdbc:mariadb://localhost:3306/articulos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=Aschmadia
spring.datasource.password=nrrvZkf097t5a!o#yLZXLj
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true